% 滤波器提取呼吸、心跳信号



% diff_params.n = length(f_diff);                                                 % 差分信号点数
% diff_params.fs = diff_params.n / radar_params.total_time ;                      % 差分信号采样速率
% diff_params.time_lin = linspace(1,radar_params.total_time,diff_params.n);       % 差分信号 时间坐标轴
% diff_params.freq_lin = (0:diff_params.n - 1) * (diff_params.fs / diff_params.n);% 差分信号 频率坐标轴


function  [f_heart_filt,f_beath_filt]= my_filter(f_input,diff_params)

    

    % COE2 --> 心跳
    COE2=chebyshev_IIR2(diff_params.fs);
    f_heart_filt = filter(COE2,f_input); 

    % COE1 --> 呼吸
    COE1 = chebyshev_IIR(diff_params.fs);
    f_beath_filt = filter(COE1,f_input);


    figure(Name = 'band pass filter');
    show_points = 300;
    subplot(2,2,1);
    plot(diff_params.time_lin,f_heart_filt,'r'); 
    title('心跳信号'); 
    xlabel('t/s');


    subplot(2,2,2);
    f_heart_filt_fft = fft(f_heart_filt);
    plot(diff_params.freq_lin(1:show_points),abs(f_heart_filt_fft(1:show_points))./ max(abs(f_heart_filt_fft)),'r'); 
    title('心跳信号频谱'); 
    xlabel('频率(Hz)');

    subplot(2,2,3);
    plot(diff_params.time_lin,f_beath_filt); title('呼吸信号'); xlabel('t/s');

    subplot(2,2,4);
    f_beath_filt_fft = fft(f_beath_filt);
    plot(diff_params.freq_lin(1:show_points),abs(f_beath_filt_fft(1:show_points))./ max(abs(f_beath_filt_fft)));
    title('呼吸信号频谱');
    xlabel('频率(Hz)');


end






% ----------------------------------------------------------------

function Hd = chebyshev_IIR(Fs)
    %CHEBYSHEV_IIR 返回离散时间滤波器对象。
    
    % MATLAB Code
    % Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
    % Generated on: 06-May-2022 09:49:00
    
    % Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.
    
    % All frequency values are in Hz.
    % Fs = 100;  % Sampling Frequency
    
    Fstop1 = 0.05;        % First Stopband Frequency
    Fpass1 = 0.1;         % First Passband Frequency
    Fpass2 = 0.5;         % Second Passband Frequency
    Fstop2 = 0.55;        % Second Stopband Frequency
    Astop1 = 60;          % First Stopband Attenuation (dB)
    Apass  = 3;           % Passband Ripple (dB)
    Astop2 = 60;          % Second Stopband Attenuation (dB)
    match  = 'passband';  % Band to match exactly
    
    % Construct an FDESIGN object and call its CHEBY1 method.
    h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                            Astop2, Fs);
    Hd = design(h, 'cheby1', 'MatchExactly', match);
    
    % [EOF]
end


function Hd = chebyshev_IIR2(Fs)
    %CHEBYSHEV_IIR 返回离散时间滤波器对象。
    
    % MATLAB Code
    % Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
    % Generated on: 06-May-2022 09:49:00
    
    % Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.
    
    % All frequency values are in Hz.
    % Fs = 100;  % Sampling Frequency
    
    Fstop1 = 0.7;        % First Stopband Frequency
    Fpass1 = 0.8;         % First Passband Frequency
    Fpass2 = 2;         % Second Passband Frequency
    Fstop2 = 2.01;        % Second Stopband Frequency
    Astop1 = 30;          % First Stopband Attenuation (dB)
    Apass  = 3;           % Passband Ripple (dB)
    Astop2 = 60;          % Second Stopband Attenuation (dB)
    match  = 'passband';  % Band to match exactly
    
    % Construct an FDESIGN object and call its CHEBY1 method.
    h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                            Astop2, Fs);
    Hd = design(h, 'cheby1', 'MatchExactly', match);
    
    % [EOF]
end